// This file is automatically generated by vscode-react-native@0.2.5
// Please do not modify it manually. All changes will be lost.
var React = require('/Users/emrahkucukkaya/CODE/LoginPages/node_modules/react');
var {Component} = React;

var ReactNative = require('/Users/emrahkucukkaya/CODE/LoginPages/node_modules/react-native');
var {AppRegistry} = ReactNative;

var entryPoint = require('/Users/emrahkucukkaya/CODE/LoginPages/index.ios.js');

AppRegistry.registerRunnable('main', function(appParameters) {
    AppRegistry.runApplication('LoginPages', appParameters);
});